from polymarket_pandas._version import __version__
from polymarket_pandas.async_client import AsyncPolymarketPandas
from polymarket_pandas.async_ws import (
    AsyncPolymarketWebSocket,
    AsyncPolymarketWebSocketSession,
)
from polymarket_pandas.client import PolymarketPandas
from polymarket_pandas.exceptions import (
    PolymarketAPIError,
    PolymarketAuthError,
    PolymarketError,
    PolymarketRateLimitError,
)
from polymarket_pandas.order_schema import (
    OrderSchema,
    PlaceOrderSchema,
    SubmitOrderSchema,
)
from polymarket_pandas.parsers import (
    classify_event_structure,
    coalesce_end_date_from_title,
    parse_title_bounds,
    parse_title_sports,
    parse_title_threshold,
)
from polymarket_pandas.schemas import (
    ActiveOrderSchema,
    ActivitySchema,
    BridgeSupportedAssetSchema,
    BridgeTransactionSchema,
    BuilderLeaderboardSchema,
    BuilderTradeSchema,
    BuilderVolumeSchema,
    ClobTradeSchema,
    ClosedPositionSchema,
    CommentSchema,
    CurrentRewardSchema,
    DataTradeSchema,
    EventSchema,
    LastTradePricesSchema,
    LeaderboardSchema,
    MarketPriceSchema,
    MarketSchema,
    MidpointSchema,
    OrderbookSchema,
    PositionSchema,
    PositionValueSchema,
    PriceHistorySchema,
    RebateSchema,
    RewardsMarketMultiSchema,
    RewardsMarketSchema,
    SamplingMarketSchema,
    SendOrderResponseSchema,
    SeriesSchema,
    SimplifiedMarketSchema,
    SportsMetadataSchema,
    TagSchema,
    TeamSchema,
    UserEarningSchema,
    UserRewardsMarketSchema,
    XTrackerDailyStatSchema,
    XTrackerMetricSchema,
    XTrackerPostSchema,
    XTrackerTrackingSchema,
    XTrackerUserSchema,
)
from polymarket_pandas.types import (
    ApiCredentials,
    BalanceAllowance,
    BridgeAddress,
    BridgeAddressInfo,
    BuilderTradesCursorPage,
    CancelOrdersResponse,
    CurrentRewardsCursorPage,
    CursorPage,
    GasEstimate,
    LastTradePrice,
    OrdersCursorPage,
    RelayPayload,
    RewardsMarketCursorPage,
    RewardsMarketMultiCursorPage,
    SamplingMarketsCursorPage,
    SendOrderResponse,
    SignedOrder,
    SimplifiedMarketsCursorPage,
    SubmitTransactionResponse,
    TransactionReceipt,
    UserEarningsCursorPage,
    UserRewardsMarketsCursorPage,
    UserTradesCursorPage,
    XTrackerTracking,
    XTrackerUser,
)
from polymarket_pandas.ws import PolymarketWebSocket, PolymarketWebSocketSession

__all__ = [
    "__version__",
    # Clients
    "AsyncPolymarketPandas",
    "AsyncPolymarketWebSocket",
    "AsyncPolymarketWebSocketSession",
    "PolymarketPandas",
    "PolymarketWebSocket",
    "PolymarketWebSocketSession",
    # Exceptions
    "PolymarketError",
    "PolymarketAPIError",
    "PolymarketAuthError",
    "PolymarketRateLimitError",
    # TypedDicts — cursor-paginated responses
    "CursorPage",
    "BuilderTradesCursorPage",
    "CurrentRewardsCursorPage",
    "OrdersCursorPage",
    "RewardsMarketCursorPage",
    "RewardsMarketMultiCursorPage",
    "SamplingMarketsCursorPage",
    "SimplifiedMarketsCursorPage",
    "UserEarningsCursorPage",
    "UserRewardsMarketsCursorPage",
    "UserTradesCursorPage",
    # TypedDicts — other dict responses
    "ApiCredentials",
    "GasEstimate",
    "BalanceAllowance",
    "BridgeAddress",
    "BridgeAddressInfo",
    "CancelOrdersResponse",
    "LastTradePrice",
    "RelayPayload",
    "SendOrderResponse",
    "SignedOrder",
    "SubmitTransactionResponse",
    "TransactionReceipt",
    "XTrackerTracking",
    "XTrackerUser",
    # Pandera schemas (order input validation)
    "OrderSchema",
    "PlaceOrderSchema",
    "SubmitOrderSchema",
    # Pandera schemas (DataFrame-returning endpoints)
    "ActiveOrderSchema",
    "ActivitySchema",
    "BridgeSupportedAssetSchema",
    "BridgeTransactionSchema",
    "BuilderLeaderboardSchema",
    "BuilderTradeSchema",
    "BuilderVolumeSchema",
    "ClobTradeSchema",
    "ClosedPositionSchema",
    "CommentSchema",
    "CurrentRewardSchema",
    "DataTradeSchema",
    "EventSchema",
    "LastTradePricesSchema",
    "LeaderboardSchema",
    "MarketPriceSchema",
    "MarketSchema",
    "MidpointSchema",
    "OrderbookSchema",
    "PositionSchema",
    "PositionValueSchema",
    "PriceHistorySchema",
    "RebateSchema",
    "RewardsMarketMultiSchema",
    "RewardsMarketSchema",
    "SamplingMarketSchema",
    "SendOrderResponseSchema",
    "SeriesSchema",
    "SimplifiedMarketSchema",
    "SportsMetadataSchema",
    "TagSchema",
    "TeamSchema",
    "UserEarningSchema",
    "UserRewardsMarketSchema",
    "XTrackerDailyStatSchema",
    "XTrackerMetricSchema",
    "XTrackerPostSchema",
    "XTrackerTrackingSchema",
    "XTrackerUserSchema",
    # DataFrame parsers / enrichers
    "classify_event_structure",
    "coalesce_end_date_from_title",
    "parse_title_bounds",
    "parse_title_sports",
    "parse_title_threshold",
]
